### ISSUE TITLE
Scan local directory tree

### ISSUE THREAD

**Issue by ralfbergs** [kootenpv/gittyleaks#22]
It doesn't seem to be possible to scan a local directory tree -- would that not be a nice addition and something many people would expect  from  such a  tool?

**Comment by kootenpv** [comment]
Just run `gittyleaks` in your directory

**Comment by ralfbergs** [comment]
Sorry if I was not specific enough.

I'm not talking about a locally "cloned" Git repo. I'm talking about simply any arbitrary directory containing files that should be scanned whether to contain sensitive material.

Can this be done?

**Comment by kootenpv** [comment]
Nope, because all the commands are really built around git (for example revision list, it searches through the whole history not just a directory).

I suppose it could be made to work with a refactor, but by the name `gittyleaks` it does seem a bit out of scope.

If you wanted to make a PR I would accept it, but since this request came 6 years after its inception I don't think it's such an often demanded feature...
