### ISSUE TITLE
The --excluding option does not appear to work

### ISSUE THREAD

**Issue by biggianteye** [kootenpv/gittyleaks#9]
I am testing this out on a repo that contains a class called `Token`. This is a symbol that appears in the output of gittyleaks and so I want to exclude it. I tried using the `--excluding` option like so:

```
gittyleaks --excluding Token
```

Unfortunately, this symbol still appears a lot in the output.

```
$ gittyleaks --excluding Token | grep Token | wc -l
     333
```

I did a diff of output with and without the `--excluding` parameter and it *is* doing some filtering but only of lines of this form:

```
$token = ...
```

Have I misunderstood what this parameter does? How can I skip flagging of this symbol?

**Comment by kootenpv** [comment]
Hi, thanks for taking the time to post an issue.

I had to dive into it because it has been a long time.

What I've discovered is that `excluding` is more about the value.

E.g. using `--excluding Token`, you can exclude:

    password = "token"

But

    password = "mypass"  # token

would still be included.

I guess this is quite weird behavior and I am not sure why I implemented it like this (though I could see this is potentially useful).

However, I must ask, is there a reason why you wouldn't just:

    gittyleaks | grep -v Token

As in... are you just confused with the current behavior? 

EDIT: surprisingly it is in the help of `--excluding`: `'List of words that are ignored occurring as value.'`. But I am still unsure why.

**Comment by biggianteye** [comment]
I guess I must have missed the key part: "occurring as value". I thought it covered everything. Thanks for checking for me. 👍
